USE [master]
GO
/****** Object:  Database [BelagricolaQ4]    Script Date: 22/12/2022 11:46:37 ******/
CREATE DATABASE [BelagricolaQ4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BelagricolaQ4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BelagricolaQ4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BelagricolaQ4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BelagricolaQ4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BelagricolaQ4] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BelagricolaQ4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BelagricolaQ4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET ARITHABORT OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BelagricolaQ4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BelagricolaQ4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BelagricolaQ4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BelagricolaQ4] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [BelagricolaQ4] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET RECOVERY FULL 
GO
ALTER DATABASE [BelagricolaQ4] SET  MULTI_USER 
GO
ALTER DATABASE [BelagricolaQ4] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BelagricolaQ4] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BelagricolaQ4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BelagricolaQ4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BelagricolaQ4] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BelagricolaQ4] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BelagricolaQ4', N'ON'
GO
ALTER DATABASE [BelagricolaQ4] SET QUERY_STORE = OFF
GO
USE [BelagricolaQ4]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 22/12/2022 11:46:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 22/12/2022 11:46:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Cpf] [nvarchar](14) NOT NULL,
	[Email] [nvarchar](150) NOT NULL,
	[Nome] [nvarchar](255) NOT NULL,
	[Telefone] [nvarchar](15) NULL,
	[Celular] [nvarchar](15) NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ClienteContatos]    Script Date: 22/12/2022 11:46:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ClienteContatos](
	[ClienteCodigo] [int] NOT NULL,
	[ContatoCodigo] [int] NOT NULL,
	[TipoRelacionamento] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_ClienteContatos] PRIMARY KEY CLUSTERED 
(
	[ClienteCodigo] ASC,
	[ContatoCodigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contato]    Script Date: 22/12/2022 11:46:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contato](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](255) NOT NULL,
	[Telefone] [nvarchar](15) NULL,
	[Celular] [nvarchar](15) NULL,
 CONSTRAINT [PK_Contato] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_ClienteContatos_ContatoCodigo]    Script Date: 22/12/2022 11:46:37 ******/
CREATE NONCLUSTERED INDEX [IX_ClienteContatos_ContatoCodigo] ON [dbo].[ClienteContatos]
(
	[ContatoCodigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ClienteContatos]  WITH CHECK ADD  CONSTRAINT [FK_ClienteContatos_Cliente_ClienteCodigo] FOREIGN KEY([ClienteCodigo])
REFERENCES [dbo].[Cliente] ([Codigo])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ClienteContatos] CHECK CONSTRAINT [FK_ClienteContatos_Cliente_ClienteCodigo]
GO
ALTER TABLE [dbo].[ClienteContatos]  WITH CHECK ADD  CONSTRAINT [FK_ClienteContatos_Contato_ContatoCodigo] FOREIGN KEY([ContatoCodigo])
REFERENCES [dbo].[Contato] ([Codigo])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ClienteContatos] CHECK CONSTRAINT [FK_ClienteContatos_Contato_ContatoCodigo]
GO
USE [master]
GO
ALTER DATABASE [BelagricolaQ4] SET  READ_WRITE 
GO
